{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baf.codeid.flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3970365,
          "sha512": "35be5d4fb6945c2cefda3455941bf55d672fb3ba45bdc5bfa45f5561e5681e827baf3ed225b40c3c73e8412e2d312072caa28034174d8435236549adb1ff7f88",
          "sha256": "c4540558002102d94fe9988f4eb4837f13b011eab664b441279c97e84eab8897",
          "sha1": "9aeaf82b2a0e4855c019e42c51c382efb4183e64",
          "md5": "f424bac35fe8c7fc7a1a72ab32314ec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-235db911ba279722f5e685f38b0ed30fa7e8570a"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3970365,
          "sha512": "35be5d4fb6945c2cefda3455941bf55d672fb3ba45bdc5bfa45f5561e5681e827baf3ed225b40c3c73e8412e2d312072caa28034174d8435236549adb1ff7f88",
          "sha256": "c4540558002102d94fe9988f4eb4837f13b011eab664b441279c97e84eab8897",
          "sha1": "9aeaf82b2a0e4855c019e42c51c382efb4183e64",
          "md5": "f424bac35fe8c7fc7a1a72ab32314ec2"
        }
      ]
    }
  ]
}
